spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://practice.cycfrbihifri.ap-northeast-2.rds.amazonaws.com:3306/practice
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
      open-in-view: false
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
