spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restAPI?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: nsgg9577;;
  jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true